/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mario;

import org.junit.Test;

public class LibraryTest {
     public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

	private void assertTrue(String string, boolean someLibraryMethod) {
		// TODO Auto-generated method stub
		
	}
}
